server:
  port: 51805
spring:
  application:
    name: leadnews-behavior
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
  config:
    import: "consul:"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leadnews_behavior?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: behavior-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
