server:
  port: 51801
spring:
  config:
    import: "consul:"

  application:
    name: leadnews-user
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
    openfeign:
      client:
        config:
          default:
            connectTimeout: 20000
            readTimeout: 20000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leadnews_user?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
