server:
  port: 9998
spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
  config:
    import: "consul:"
  data:
    mongodb:
      host: localhost
      port: 27017
      database: leadnews-history