server:
  port: 51701
spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
  config:
    import: "consul:"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leadnews_schedule?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 707161
  redis:
    host: localhost
    password: leadnews
    port: 6379
mybatis-plus:
    mapper-locations: classpath*:mapper/*.xml
    type-aliases-package: com.news.model.schedule.pojos