server:
  port: 51602
spring:
  application:
    name: leadnews-wemedia-gateway
  config:
    import: "consul:"
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
    gateway:
      server:
        webflux:
          globalcors:
            add-to-simple-url-handler-mapping: true
            corsConfigurations:
              '[/**]':
                allowedHeaders: "*"
                allowedOrigins: "*"
                allowedMethods:
                  - GET
                  - POST
                  - DELETE
                  - PUT
                  - OPTIONS
          routes:
            - id: wemedia
              uri: lb://leadnews-wemedia
              predicates:
                - Path=/wemedia/**
              filters:
                - StripPrefix=1
